------------------------------------------------------------------------------------------------------------------------
-- Создание индексов для потенциально наиболее необходимых полей в таблицах
------------------------------------------------------------------------------------------------------------------------
CREATE INDEX IDX_AIRCRAFT_MODEL ON AIRCRAFT (MODEL);

CREATE INDEX IDX_AIRPORT_NAME ON AIRPORT (NAME);

CREATE INDEX IDX_AIRPORT_CITY_COUNTRY ON AIRPORT (CITY, COUNTRY);

CREATE INDEX IDX_CUSTOMER_EMAIL ON CUSTOMER (EMAIL);

CREATE INDEX IDX_CUSTOMER_PHONE ON CUSTOMER (PHONE);

CREATE INDEX IDX_SERVICE_CLASSES_INFO ON SERVICE_CLASSES_INFO (
                                                               ECONOMY_CLASS_TOTAL_SEATS,
                                                               BUSINESS_CLASS_TOTAL_SEATS
    );

CREATE INDEX IDX_FLIGHT_SERVICE_AIRCRAFT_ID ON FLIGHT_SERVICE (AIRCRAFT_ID);

CREATE INDEX IDX_FLIGHT_BOOKINGS_ECONOMY_CLASS_SEATS_BOOKED ON FLIGHT_BOOKINGS (ECONOMY_CLASS_SEATS_BOOKED);

CREATE INDEX IDX_FLIGHT_BOOKINGS_BUSINESS_CLASS_SEATS_BOOKED ON FLIGHT_BOOKINGS (BUSINESS_CLASS_SEATS_BOOKED);

CREATE INDEX IDX_FLIGHT_FLIGHT_NUMBER ON FLIGHT (FLIGHT_NUMBER);

CREATE INDEX IDX_FLIGHT_DEPARTURE_AIRPORT ON FLIGHT (DEPARTURE_AIRPORT_ID);

CREATE INDEX IDX_FLIGHT_ARRIVAL_AIRPORT ON FLIGHT (ARRIVAL_AIRPORT_ID);

CREATE INDEX IDX_FLIGHT_DEPARTURE_DATE ON FLIGHT (DEPARTURE_DATE);

CREATE INDEX IDX_FLIGHT_ARRIVAL_DATE ON FLIGHT (ARRIVAL_DATE);

CREATE INDEX IDX_BOOKING_CUSTOMER_ID ON BOOKING (CUSTOMER_ID);

CREATE INDEX IDX_BOOKING_FLIGHT_ID ON BOOKING (FLIGHT_ID);

CREATE INDEX IDX_BOOKING_PAYMENT_METHOD ON BOOKING (PAYMENT_METHOD);

CREATE INDEX IDX_PASSENGER_PASSPORT_NUMBER ON PASSENGER (PASSPORT_NUMBER);

CREATE INDEX IDX_PASSENGER_BOOKING_ID ON PASSENGER (BOOKING_ID);

CREATE INDEX IDX_EMPLOYEE_OCCUPATION ON EMPLOYEE (OCCUPATION);

CREATE INDEX IDX_EMPLOYEE_FLIGHT_SERVICE_ID ON EMPLOYEE (FLIGHT_SERVICE_ID);